/**
 * How a role is presented, in one place.
 *
 * The strings existed twice already — `TABS` in the identity picker and
 * `ROLE_LABELS` in the admin users page — and the header now needs them a third
 * time, so they live here. The picker keeps its own table: it carries a noun,
 * an article, a hint and a join label besides the name, and deliberately has no
 * admin entry, because an admin must not be mintable from a signup form.
 *
 * The icons are the existing set, not new art: `public/icons/` is generated by
 * `tools/artgen/gen.py`, which needs an API key for any name it has not already
 * cached, so a new glyph is not free. These three read well enough as they are
 * — a ticket for the person holding a seat, a clipboard for the person running
 * the table, a shield for the operator.
 */

import type { Role } from "../../shared/api-types";
import type { IconName } from "../components/Icon";

export const ROLE_LABELS: Record<Role, string> = {
  player: "Player",
  organizer: "Organizer",
  admin: "Admin",
};

export const ROLE_ICONS: Record<Role, IconName> = {
  player: "mine",
  organizer: "organize",
  admin: "shield",
};
