/**
 * How a role is presented, in one place.
 *
 * The strings existed twice already — `TABS` in the identity picker and
 * `ROLE_LABELS` in the admin users page — and the header now needs them a third
 * time, so they live here. The picker keeps its own table: it carries a noun,
 * an article and a join label besides the name, and deliberately has no
 * admin entry, because an admin must not be mintable from a signup form.
 *
 * The icons come from `public/icons/`, generated by `tools/artgen/gen.py`: a
 * silhouette for the person who turns up, a clipboard for the person running
 * the table, a shield for the operator. The silhouette replaced a ticket, which
 * described what a player *holds* rather than who they are — and the same glyph
 * now marks both this badge and the "My RSVP" tab, so the two agree.
 */

import type { Role } from "../../shared/api-types";
import type { IconName } from "../components/Icon";

export const ROLE_LABELS: Record<Role, string> = {
  player: "Player",
  organizer: "Organizer",
  admin: "Admin",
};

export const ROLE_ICONS: Record<Role, IconName> = {
  player: "player",
  organizer: "organize",
  admin: "shield",
};
