/**
 * The address, as a tap that actually goes somewhere.
 *
 * `mapsSearchUrl` needs no API key and opens the native Maps app on both
 * phones, so this works in every deployment including one with no key at all —
 * it is the half of the feature that is always on.
 *
 * The pin is inline SVG rather than `<Icon name="…" />` on purpose. That icon
 * set is PNG masks generated by `tools/artgen/gen.py`, which needs an API key
 * to run; adding a build-time asset dependency for one 24×24 glyph is a bad
 * trade. `fill="currentColor"` keeps it in step with the surrounding text in
 * both themes.
 */

import { mapsSearchUrl, type MappableEvent } from "../../shared/maps-links";

export function MapLink({
  event,
  className = "card__address",
  compact = false,
  withAddress = false,
}: {
  event: MappableEvent;
  className?: string;
  /**
   * Put Google's canonical address inside the link, under the label.
   *
   * It used to sit outside as its own paragraph, and looked wrong for a reason
   * worth writing down: the label is a 44px tap target with its text centred,
   * so there was ~15px of empty box between the words and the address — a gap
   * nothing had put there on purpose. Inside, the two are lines of one control:
   * the gap is ordinary line spacing, and the address becomes part of what you
   * can tap rather than a caption sitting under it.
   */
  withAddress?: boolean;
  /**
   * Draw the venue, don't link it.
   *
   * On a card this is one muted line among three, and a link there has to carry
   * a 44px tap target for a label nobody came to tap — the address is the one
   * thing the detail sheet is guaranteed to have room for. So the card gets the
   * pin and the words, and the sheet keeps the link.
   */
  compact?: boolean;
}) {
  if (compact) {
    return (
      <span className="ecard__venue">
        <MapPin />
        <span className="ecard__venue-text">{event.location}</span>
      </span>
    );
  }
  // Only when it says something the label does not already say.
  const address = withAddress && event.place && event.place.address !== event.location ? event.place.address : null;

  return (
    <a className={className} href={mapsSearchUrl(event)} target="_blank" rel="noopener noreferrer">
      <MapPin />
      {address === null ? (
        <span className="card__address-text">{event.location}</span>
      ) : (
        <span className="venue__lines">
          <span className="card__address-text">{event.location}</span>
          <span className="venue__address">{address}</span>
        </span>
      )}
      <span className="visually-hidden"> — opens in Google Maps</span>
    </a>
  );
}

function MapPin() {
  return (
    <svg
      className="card__address-pin"
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M12 2a7 7 0 0 0-7 7c0 5.05 6.2 12.2 6.47 12.5a.7.7 0 0 0 1.06 0C12.8 21.2 19 14.05 19 9a7 7 0 0 0-7-7Zm0 9.6A2.6 2.6 0 1 1 12 6.4a2.6 2.6 0 0 1 0 5.2Z" />
    </svg>
  );
}
